### ISSUE TITLE
Enhanced Download Management Options

### ISSUE THREAD

**Issue by gabrielmoura** [StefanLobbenmeier/youtube-dl-gui#116]
Hi.

I would like to suggest the inclusion of an option to pause the download and resume it later, or even the possibility to change the queue order. This becomes relevant because some sites restrict the number of downloads per IP address, and I believe it would be helpful to be able to group downloads and select the queue order by group.

Thank you in advance for any response or viable solution.

**Comment by StefanLobbenmeier** [comment]
There are a lot of separate ideas here:

- pause/resume: I will absolutely implement this. Yt-dlp does not have the concept of „pausing“, but you can cancel a download and it is able to resume it, so that is something we can support
- restricted downloads per ip address - I would say this is already supported well with the setting to limit number of concurrent downloads
- reordering the queue - this is tricky to implement both code and UX wise. I think we could do a button to ignore the limit and start immediately, and a button to put the current download to the head of the queue, which would hopefully be good enough for most prioritization needs?

**Comment by gabrielmoura** [comment]
Thank you for your reply.
