### ISSUE TITLE
Financial contribution

### ISSUE THREAD

**Issue by horiaconstantin-cpi** [StefanLobbenmeier/youtube-dl-gui#72]
I celebrate that this project exists. 
And I was wondering, where is a link to contribute/support financially this project? I hate it when great projects die off because the maintainer doesn't have any more energy to maintain. (this already happened once for this project)
Would you be willing to setup something?

**Comment by StefanLobbenmeier** [comment]
Hey 😄 did not really look into taking donations since noone offered so far. Currently my main motivation is that someone in my family is using the application, so I usually work on it whenever he has some issues 😛 

If you do want to donate, I will look into ways to do that. I have not accepted donations anywhere so it might take some research, but I heard of PayPal, kofi and Github Sponsors as solutions

**Comment by StefanLobbenmeier** [comment]
So I set up a rudimentary kofi page:
https://ko-fi.com/stefanlobbenmeier

For GitHub sponsors I need to look into this later this week.

**Comment by StefanLobbenmeier** [comment]
Also thank you very much for your support ❤️  

If there is some other method you would prefer I can also look into it 😄

**Comment by StefanLobbenmeier** [comment]
Yeah looks like I received the whole amount. Thank you very much 😄

**Comment by StefanLobbenmeier** [comment]
Just added the kofi link to the readme as well

**Comment by StefanLobbenmeier** [comment]
I also applied to GitHub sponsors, but looks like that is a longer process / will be reviewed by GitHub
